/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_metrics_ThroughputMeasurement */

#ifndef _Included_net_bitmovin_libdash_metrics_ThroughputMeasurement
#define _Included_net_bitmovin_libdash_metrics_ThroughputMeasurement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    StartOfPeriod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_StartOfPeriod
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    DurationOfPeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_DurationOfPeriod
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    ReceivedBytesPerTrace
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_ReceivedBytesPerTrace
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    SetStartOfPeriod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_SetStartOfPeriod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    SetDurationOfPeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_SetDurationOfPeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_bitmovin_libdash_metrics_ThroughputMeasurement
 * Method:    AddReceivedBytes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_ThroughputMeasurement_AddReceivedBytes
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
