/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_ProgramInformation */

#ifndef _Included_net_bitmovin_libdash_mpd_ProgramInformation
#define _Included_net_bitmovin_libdash_mpd_ProgramInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetTitle
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetSource
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetSource
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetCopyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetCopyright
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetLang
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetLang
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetMoreInformationURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetMoreInformationURL
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    SetTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_SetTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    SetSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_SetSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    SetCopyright
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_SetCopyright
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    SetLang
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_SetLang
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    SetMoreInformationURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_SetMoreInformationURL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ProgramInformation
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_ProgramInformation_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
