/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_metrics_TCPConnection */

#ifndef _Included_net_bitmovin_libdash_metrics_TCPConnection
#define _Included_net_bitmovin_libdash_metrics_TCPConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    TCPId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_TCPId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    DestinationAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_DestinationAddress
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    ConnectionOpenedTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_ConnectionOpenedTime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    ConnectionClosedTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_ConnectionClosedTime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    ConnectionTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_ConnectionTime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    SetTCPId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_SetTCPId
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    SetDestinationAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_SetDestinationAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    SetConnectionOpenedTime
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_SetConnectionOpenedTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    SetConnectionClosedTime
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_SetConnectionClosedTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_metrics_TCPConnection
 * Method:    SetConnectionTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_metrics_TCPConnection_SetConnectionTime
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
