/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_MultipleSegmentBase */

#ifndef _Included_net_bitmovin_libdash_mpd_MultipleSegmentBase
#define _Included_net_bitmovin_libdash_mpd_MultipleSegmentBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    GetSegmentTimeline
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentTimeline;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_GetSegmentTimeline
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    GetBitstreamSwitching
 * Signature: ()Lnet/bitmovin/libdash/mpd/IURLType;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_GetBitstreamSwitching
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    GetDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_GetDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    GetStartNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_GetStartNumber
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    SetSegmentTimeline
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentTimeline;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_SetSegmentTimeline
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    SetBitstreamSwitching
 * Signature: (Lnet/bitmovin/libdash/mpd/URLType;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_SetBitstreamSwitching
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    SetDuration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_SetDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_MultipleSegmentBase
 * Method:    SetStartNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_MultipleSegmentBase_SetStartNumber
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
