/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_xml_DOMHelper */

#ifndef _Included_net_bitmovin_libdash_xml_DOMHelper
#define _Included_net_bitmovin_libdash_xml_DOMHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_xml_DOMHelper
 * Method:    GetElementByTagName
 * Signature: (Lnet/bitmovin/libdash/xml/Node;Ljava/lang/String;Z)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_DOMHelper_GetElementByTagName
  (JNIEnv *, jclass, jobject, jstring, jboolean);

/*
 * Class:     net_bitmovin_libdash_xml_DOMHelper
 * Method:    GetChildElementByTagName
 * Signature: (Lnet/bitmovin/libdash/xml/Node;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_DOMHelper_GetChildElementByTagName
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
