/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_Range */

#ifndef _Included_net_bitmovin_libdash_mpd_Range
#define _Included_net_bitmovin_libdash_mpd_Range
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_Range
 * Method:    GetStarttime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Range_GetStarttime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Range
 * Method:    GetDuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Range_GetDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Range
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_Range_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Range
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Range_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Range
 * Method:    SetStarttime
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Range_SetStarttime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Range
 * Method:    SetDuration
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Range_SetDuration
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
