/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_SubRepresentation */

#ifndef _Included_net_bitmovin_libdash_mpd_SubRepresentation
#define _Included_net_bitmovin_libdash_mpd_SubRepresentation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    GetLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_GetLevel
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    GetDependencyLevel
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_GetDependencyLevel
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    GetBandWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_GetBandWidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    GetContentComponent
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_GetContentComponent
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    SetLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_SetLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    SetDependencyLevel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_SetDependencyLevel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    SetBandWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_SetBandWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    SetContentComponent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_SetContentComponent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SubRepresentation
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SubRepresentation_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
