/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_AdaptationSet */

#ifndef _Included_net_bitmovin_libdash_mpd_AdaptationSet
#define _Included_net_bitmovin_libdash_mpd_AdaptationSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetAccessibility
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetAccessibility
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetRole
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetRole
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetRating
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetRating
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetViewpoint
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetViewpoint
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetContentComponent
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetContentComponent
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetBaseURLs
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetBaseURLs
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetSegmentBase
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentBase;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetSegmentBase
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetSegmentList
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetSegmentList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetSegmentTemplate
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentTemplate;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetSegmentTemplate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetRepresentation
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetRepresentation
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetXlinkHref
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetXlinkHref
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetXlinkActuate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetXlinkActuate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetGroup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetGroup
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetLang
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetLang
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetContentType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetContentType
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetPar
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetPar
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMinBandwidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMinBandwidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMaxBandwidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMaxBandwidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMinWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMinWidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMaxWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMaxWidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMinHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMinHeight
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMaxHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMaxHeight
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMinFramerate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMinFramerate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetMaxFramerate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetMaxFramerate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SegmentAlignmentIsBoolValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SegmentAlignmentIsBoolValue
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    HasSegmentAlignment
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_HasSegmentAlignment
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetSegmentAligment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetSegmentAligment
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SubsegmentAlignmentIsBoolValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SubsegmentAlignmentIsBoolValue
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    HasSubsegmentAlignment
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_HasSubsegmentAlignment
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetSubsegmentAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetSubsegmentAlignment
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetSubsegmentStartsWithSAP
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetSubsegmentStartsWithSAP
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetBitstreamSwitching
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetBitstreamSwitching
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddAccessibity
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddAccessibity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddRole
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddRole
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddRating
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddRating
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddViewpoint
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddViewpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddContentComponent
 * Signature: (Lnet/bitmovin/libdash/mpd/ContentComponent;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddContentComponent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddBaseURL
 * Signature: (Lnet/bitmovin/libdash/mpd/BaseUrl;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddBaseURL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetSegmentBase
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentBase;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetSegmentBase
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetSegmentList
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentList;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetSegmentList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetSegmentTemplate
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentTemplate;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetSegmentTemplate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    AddRepresentation
 * Signature: (Lnet/bitmovin/libdash/mpd/Representation;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_AddRepresentation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetXlinkHref
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetXlinkHref
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetXlinkActuate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetXlinkActuate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetId
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetGroup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetGroup
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetLang
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetLang
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetContentType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetContentType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetPar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetPar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMinBandwidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMinBandwidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMaxBandwidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMaxBandwidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMinWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMinWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMaxWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMaxWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMinHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMinHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMaxHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMaxHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMinFramerate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMinFramerate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetMaxFramerate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetMaxFramerate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetSegmentAlignment
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetSegmentAlignment
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetSubsegmentAlignment
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetSubsegmentAlignment
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetSubsegmentStartsWithSAP
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetSubsegmentStartsWithSAP
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    SetBitstreamSwitching
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_SetBitstreamSwitching
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_AdaptationSet
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_AdaptationSet_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
