/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_RepresentationBase */

#ifndef _Included_net_bitmovin_libdash_mpd_RepresentationBase
#define _Included_net_bitmovin_libdash_mpd_RepresentationBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetFramePacking
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetFramePacking
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetAudioChannelConfiguration
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetAudioChannelConfiguration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetContentProtection
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetContentProtection
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetProfiles
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetProfiles
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetWidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetHeight
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetSar
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetSar
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetFrameRate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetFrameRate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetAudioSamplingRate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetAudioSamplingRate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetMimeType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetMimeType
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetSegmentProfiles
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetSegmentProfiles
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetCodecs
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetCodecs
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetMaximumSAPPeriod
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetMaximumSAPPeriod
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetStartWithSAP
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetStartWithSAP
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetMaxPlayoutRate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetMaxPlayoutRate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    HasCodingDependency
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_HasCodingDependency
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    GetScanType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_GetScanType
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    AddFramePacking
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_AddFramePacking
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    AddAudioChannelConfiguration
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_AddAudioChannelConfiguration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    AddContentProtection
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_AddContentProtection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetProfiles
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetProfiles
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetSar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetSar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetFrameRate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetFrameRate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetAudioSamplingRate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetAudioSamplingRate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetMimeType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetMimeType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetSegmentProfiles
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetSegmentProfiles
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetCodecs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetCodecs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetMaximumSAPPeriod
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetMaximumSAPPeriod
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetStartWithSAP
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetStartWithSAP
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetMaxPlayoutRate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetMaxPlayoutRate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetCodingDependency
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetCodingDependency
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_bitmovin_libdash_mpd_RepresentationBase
 * Method:    SetScanType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_RepresentationBase_SetScanType
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
