/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_DASHManager */

#ifndef _Included_net_bitmovin_libdash_DASHManager
#define _Included_net_bitmovin_libdash_DASHManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_DASHManager
 * Method:    Open
 * Signature: (Ljava/lang/String;)Lnet/bitmovin/libdash/mpd/IMPD;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_DASHManager_Open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_DASHManager
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_DASHManager_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_DASHManager
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_DASHManager_destoryCppClass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
