/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_URLType */

#ifndef _Included_net_bitmovin_libdash_mpd_URLType
#define _Included_net_bitmovin_libdash_mpd_URLType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    GetSourceURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_URLType_GetSourceURL
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    GetRange
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_URLType_GetRange
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    ToSegment
 * Signature: (Ljava/util/ArrayList;)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_URLType_ToSegment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_URLType_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_URLType_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    SetSourceURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_URLType_SetSourceURL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    SetRange
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_URLType_SetRange
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    SetType
 * Signature: (Lnet/bitmovin/libdash/metrics/HTTPTransactionType;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_URLType_SetType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_URLType_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_URLType
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_URLType_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
