/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_Representation */

#ifndef _Included_net_bitmovin_libdash_mpd_Representation
#define _Included_net_bitmovin_libdash_mpd_Representation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetBaseURLs
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetBaseURLs
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetSubRepresentations
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetSubRepresentations
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetSegmentBase
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentBase;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetSegmentBase
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetSegmentList
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetSegmentList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetSegmentTemplate
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentTemplate;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetSegmentTemplate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetBandwidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetBandwidth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetQualityRanking
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetQualityRanking
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetDependencyId
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetDependencyId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetMediaStreamStructureId
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetMediaStreamStructureId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_Representation_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    AddBaseURL
 * Signature: (Lnet/bitmovin/libdash/mpd/BaseUrl;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_AddBaseURL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    AddSubRepresentation
 * Signature: (Lnet/bitmovin/libdash/mpd/SubRepresentation;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_AddSubRepresentation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetSegmentBase
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentBase;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetSegmentBase
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetSegmentList
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentList;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetSegmentList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetSegmentTemplate
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentTemplate;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetSegmentTemplate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetBandwidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetBandwidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetQualityRanking
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetQualityRanking
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetDependencyId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetDependencyId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    SetMediaStreamStructureId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Representation_SetMediaStreamStructureId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Representation
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Representation_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
