/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_Period */

#ifndef _Included_net_bitmovin_libdash_mpd_Period
#define _Included_net_bitmovin_libdash_mpd_Period
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetBaseURLs
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetBaseURLs
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetSegmentBase
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentBase;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetSegmentBase
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetSegmentList
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetSegmentList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetSegmentTemplate
 * Signature: ()Lnet/bitmovin/libdash/mpd/ISegmentTemplate;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetSegmentTemplate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetAdaptationSets
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetAdaptationSets
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetSubsets
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetSubsets
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetXlinkHref
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Period_GetXlinkHref
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetXlinkActuate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Period_GetXlinkActuate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Period_GetId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetStart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Period_GetStart
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetDuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Period_GetDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetBitstreamSwitching
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_Period_GetBitstreamSwitching
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_Period_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    AddBaseURL
 * Signature: (Lnet/bitmovin/libdash/mpd/BaseUrl;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_AddBaseURL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetSegmentBase
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentBase;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetSegmentBase
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetSegmentList
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentList;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetSegmentList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetSegmentTemplate
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentTemplate;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetSegmentTemplate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    AddAdaptationSet
 * Signature: (Lnet/bitmovin/libdash/mpd/AdaptationSet;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_AddAdaptationSet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    AddSubset
 * Signature: (Lnet/bitmovin/libdash/mpd/Subset;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_AddSubset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetXlinkHref
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetXlinkHref
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetXlinkActuate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetXlinkActuate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetStart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetDuration
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetDuration
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    SetBitstreamSwitching
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Period_SetBitstreamSwitching
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Period
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_Period_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
