/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_Timeline */

#ifndef _Included_net_bitmovin_libdash_mpd_Timeline
#define _Included_net_bitmovin_libdash_mpd_Timeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    GetStartTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Timeline_GetStartTime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    GetDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Timeline_GetDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    GetRepeatCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Timeline_GetRepeatCount
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_Timeline_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Timeline_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    SetStartTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Timeline_SetStartTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    SetDuration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Timeline_SetDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Timeline
 * Method:    SetRepeatCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Timeline_SetRepeatCount
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
