/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_ContentComponent */

#ifndef _Included_net_bitmovin_libdash_mpd_ContentComponent
#define _Included_net_bitmovin_libdash_mpd_ContentComponent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetAccessibility
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetAccessibility
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetRole
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetRole
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetRating
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetRating
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetViewpoint
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetViewpoint
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetLang
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetLang
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetContentType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetContentType
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    GetPar
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_GetPar
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    AddAccessibity
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_AddAccessibity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    AddRole
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_AddRole
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    AddRating
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_AddRating
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    AddViewpoint
 * Signature: (Lnet/bitmovin/libdash/mpd/Descriptor;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_AddViewpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    SetId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_SetId
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    SetLang
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_SetLang
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    SetContentType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_SetContentType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_ContentComponent
 * Method:    SetPar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_ContentComponent_SetPar
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
