/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_AbstractMPDElement */

#ifndef _Included_net_bitmovin_libdash_mpd_AbstractMPDElement
#define _Included_net_bitmovin_libdash_mpd_AbstractMPDElement
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
