/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_SegmentList */

#ifndef _Included_net_bitmovin_libdash_mpd_SegmentList
#define _Included_net_bitmovin_libdash_mpd_SegmentList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    GetSegmentURLs
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_GetSegmentURLs
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    GetXlinkHref
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_GetXlinkHref
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    GetXlinkActuate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_GetXlinkActuate
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    AddSegmentURL
 * Signature: (Lnet/bitmovin/libdash/mpd/SegmentURL;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_AddSegmentURL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    SetXlinkHref
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_SetXlinkHref
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    SetXlinkActuate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_SetXlinkActuate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    GetAdditionalSubNodes
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_GetAdditionalSubNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentList
 * Method:    GetRawAttributes
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentList_GetRawAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
