#!/bin/sh

javah -verbose -classpath ../../../src net.bitmovin.libdash.DASHManager net.bitmovin.libdash.mpd.MPD net.bitmovin.libdash.mpd.BaseUrl  net.bitmovin.libdash.mpd.AbstractMPDElement net.bitmovin.libdash.mpd.ProgramInformation net.bitmovin.libdash.mpd.Descriptor net.bitmovin.libdash.mpd.RepresentationBase net.bitmovin.libdash.mpd.URLType net.bitmovin.libdash.mpd.SegmentBase net.bitmovin.libdash.mpd.ContentComponent net.bitmovin.libdash.mpd.Range net.bitmovin.libdash.mpd.Segment net.bitmovin.libdash.mpd.Timeline net.bitmovin.libdash.mpd.SegmentTimeline net.bitmovin.libdash.mpd.MultipleSegmentBase net.bitmovin.libdash.mpd.SegmentTemplate net.bitmovin.libdash.mpd.SegmentURL net.bitmovin.libdash.mpd.SegmentList net.bitmovin.libdash.mpd.SubRepresentation net.bitmovin.libdash.mpd.Representation net.bitmovin.libdash.mpd.Metrics net.bitmovin.libdash.mpd.Subset net.bitmovin.libdash.mpd.Period net.bitmovin.libdash.mpd.AdaptationSet 
javah -verbose -classpath ../../../src net.bitmovin.libdash.metrics.HTTPTransaction net.bitmovin.libdash.metrics.TCPConnection net.bitmovin.libdash.metrics.ThroughputMeasurement
javah -verbose -classpath ../../../src net.bitmovin.libdash.network.AbstractChunk net.bitmovin.libdash.network.DownloadStateManager
javah -verbose -classpath ../../../src net.bitmovin.libdash.xml.DOMHelper net.bitmovin.libdash.xml.Node net.bitmovin.libdash.xml.DOMParser

