/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_SegmentTemplate */

#ifndef _Included_net_bitmovin_libdash_mpd_SegmentTemplate
#define _Included_net_bitmovin_libdash_mpd_SegmentTemplate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    Getmedia
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_Getmedia
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    Getindex
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_Getindex
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    Getinitialization
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_Getinitialization
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    GetbitstreamSwitching
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_GetbitstreamSwitching
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    ToInitializationSegment
 * Signature: (Ljava/util/Vector;Ljava/lang/String;I)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_ToInitializationSegment
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    ToBitstreamSwitchingSegment
 * Signature: (Ljava/util/Vector;Ljava/lang/String;I)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_ToBitstreamSwitchingSegment
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    GetMediaSegmentFromNumber
 * Signature: (Ljava/util/Vector;Ljava/lang/String;II)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_GetMediaSegmentFromNumber
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    GetIndexSegmentFromNumber
 * Signature: (Ljava/util/Vector;Ljava/lang/String;II)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_GetIndexSegmentFromNumber
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    GetMediaSegmentFromTime
 * Signature: (Ljava/util/Vector;Ljava/lang/String;II)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_GetMediaSegmentFromTime
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    GetIndexSegmentFromTime
 * Signature: (Ljava/util/Vector;Ljava/lang/String;II)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_GetIndexSegmentFromTime
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    SetMedia
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_SetMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    SetIndex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_SetIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    SetInitialization
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_SetInitialization
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTemplate
 * Method:    SetBitstreamSwitching
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTemplate_SetBitstreamSwitching
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
