/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_network_AbstractChunk */

#ifndef _Included_net_bitmovin_libdash_network_AbstractChunk
#define _Included_net_bitmovin_libdash_network_AbstractChunk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    GetTCPConnectionList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_GetTCPConnectionList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    GetHTTPTransactionList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_GetHTTPTransactionList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    StartDownload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_StartDownload__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    StartDownload
 * Signature: (Lnet/bitmovin/libdash/network/IConnection;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_StartDownload__Lnet_bitmovin_libdash_network_IConnection_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    AbortDownload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_AbortDownload
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    Read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_Read
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    Peek
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_Peek
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    AttachDownloadObserver
 * Signature: (Lnet/bitmovin/libdash/network/IDownloadObserver;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_AttachDownloadObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    DetachDownloadObserver
 * Signature: (Lnet/bitmovin/libdash/network/IDownloadObserver;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_DetachDownloadObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_network_AbstractChunk
 * Method:    NotifyDownloadRateChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_network_AbstractChunk_NotifyDownloadRateChanged
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
