/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_Segment */

#ifndef _Included_net_bitmovin_libdash_mpd_Segment
#define _Included_net_bitmovin_libdash_mpd_Segment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    AbsoluteURI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Segment_AbsoluteURI__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Host
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Segment_Host__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Segment_Port__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Segment_Path__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Range
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_Segment_Range__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    StartByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Segment_StartByte__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    EndByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Segment_EndByte__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    HasByteRange
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_Segment_HasByteRange__
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    GetTypeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_Segment_GetTypeNative
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    AbsoluteURI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_AbsoluteURI__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Host
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_Host__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Port
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_Port__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Path
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_Path__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Range
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_Range__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    StartByte
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_StartByte__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    EndByte
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_EndByte__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    HasByteRange
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_HasByteRange__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_Segment_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_Segment_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_Segment
 * Method:    Init
 * Signature: (Ljava/util/ArrayList;Ljava/lang/String;Ljava/lang/String;Lnet/bitmovin/libdash/metrics/HTTPTransactionType;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_Segment_Init
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
