/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_xml_DOMParser */

#ifndef _Included_net_bitmovin_libdash_xml_DOMParser
#define _Included_net_bitmovin_libdash_xml_DOMParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_xml_DOMParser
 * Method:    initialiseCppClass
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_xml_DOMParser_initialiseCppClass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_xml_DOMParser
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_DOMParser_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_DOMParser
 * Method:    Parse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_xml_DOMParser_Parse
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_DOMParser
 * Method:    GetRootNode
 * Signature: ()Lnet/bitmovin/libdash/xml/Node;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_DOMParser_GetRootNode
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_DOMParser
 * Method:    Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_DOMParser_Print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
