/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_MPD */

#ifndef _Included_net_bitmovin_libdash_mpd_MPD
#define _Included_net_bitmovin_libdash_mpd_MPD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetTCPConnectionList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetTCPConnectionList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetHTTPTransactionList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetHTTPTransactionList
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetProgramInformations
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetProgramInformations
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetBaseUrls
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetBaseUrls
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetLocations
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetLocations
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetPeriods
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetPeriods
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMetrics
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMetrics
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetId
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetProfiles
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetProfiles
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetType
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetAvailabilityStarttime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetAvailabilityStarttime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetAvailabilityEndtime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetAvailabilityEndtime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMediaPresentationDuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMediaPresentationDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMinimumUpdatePeriod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMinimumUpdatePeriod
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMinBufferTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMinBufferTime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetTimeShiftBufferDepth
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetTimeShiftBufferDepth
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetSuggestedPresentationDelay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetSuggestedPresentationDelay
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMaxSegmentDuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMaxSegmentDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMaxSubsegmentDuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMaxSubsegmentDuration
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetMPDPathBaseUrl
 * Signature: ()Lnet/bitmovin/libdash/mpd/IBaseUrl;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetMPDPathBaseUrl
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    GetFetchTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_MPD_GetFetchTime
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_MPD_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_MPD
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_MPD_destoryCppClass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
