/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_xml_Node */

#ifndef _Included_net_bitmovin_libdash_xml_Node
#define _Included_net_bitmovin_libdash_xml_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetNodes
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_Node_GetNodes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetAttributeKeys
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_Node_GetAttributeKeys
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_xml_Node_GetName
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_xml_Node_GetText
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetAttributes
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_Node_GetAttributes
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_xml_Node_GetType
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    GetAttributeValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_xml_Node_GetAttributeValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    HasAttribute
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_xml_Node_HasAttribute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    HasText
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_xml_Node_HasText
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_xml_Node_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    SetType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_SetType
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    AddSubNode
 * Signature: (Lnet/bitmovin/libdash/xml/Node;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_AddSubNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    SetName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_SetName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    AddAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_AddAttribute
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    SetText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_SetText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    ToMPD
 * Signature: ()Lnet/bitmovin/libdash/mpd/MPD;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_xml_Node_ToMPD
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_xml_Node
 * Method:    SetMPDPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_xml_Node_SetMPDPath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
