/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_BaseUrl */

#ifndef _Included_net_bitmovin_libdash_mpd_BaseUrl
#define _Included_net_bitmovin_libdash_mpd_BaseUrl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_BaseUrl
 * Method:    GetUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_BaseUrl_GetUrl
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_BaseUrl
 * Method:    GetServiceLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_BaseUrl_GetServiceLocation
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_BaseUrl
 * Method:    GetByteRange
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_BaseUrl_GetByteRange
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_BaseUrl
 * Method:    ToMediaSegment
 * Signature: (Ljava/util/Vector;)Lnet/bitmovin/libdash/mpd/ISegment;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_BaseUrl_ToMediaSegment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_BaseUrl
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_BaseUrl_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_BaseUrl
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_BaseUrl_destoryCppClass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
