/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_SegmentTimeline */

#ifndef _Included_net_bitmovin_libdash_mpd_SegmentTimeline
#define _Included_net_bitmovin_libdash_mpd_SegmentTimeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTimeline
 * Method:    GetTimelines
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentTimeline_GetTimelines
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTimeline
 * Method:    initialiseCppClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bitmovin_libdash_mpd_SegmentTimeline_initialiseCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTimeline
 * Method:    destoryCppClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTimeline_destoryCppClass
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentTimeline
 * Method:    AddTimeline
 * Signature: (Lnet/bitmovin/libdash/mpd/Timeline;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentTimeline_AddTimeline
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
