/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitmovin_libdash_mpd_SegmentBase */

#ifndef _Included_net_bitmovin_libdash_mpd_SegmentBase
#define _Included_net_bitmovin_libdash_mpd_SegmentBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    GetInitialization
 * Signature: ()Lnet/bitmovin/libdash/mpd/IURLType;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_GetInitialization
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    GetRepresentationIndex
 * Signature: ()Lnet/bitmovin/libdash/mpd/IURLType;
 */
JNIEXPORT jobject JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_GetRepresentationIndex
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    GetTimescale
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_GetTimescale
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    GetPresentationTimeOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_GetPresentationTimeOffset
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    GetIndexRange
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_GetIndexRange
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    HasIndexRangeExact
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_HasIndexRangeExact
  (JNIEnv *, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    SetInitialization
 * Signature: (Lnet/bitmovin/libdash/mpd/URLType;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_SetInitialization
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    SetRepresentationIndex
 * Signature: (Lnet/bitmovin/libdash/mpd/URLType;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_SetRepresentationIndex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    SetTimescale
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_SetTimescale
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    SetPresentationTimeOffset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_SetPresentationTimeOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    SetIndexRange
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_SetIndexRange
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bitmovin_libdash_mpd_SegmentBase
 * Method:    SetIndexRangeExact
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_bitmovin_libdash_mpd_SegmentBase_SetIndexRangeExact
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
